// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYXUimaE6FOKiw3x08K0YGQc6lIbw4-pA',
    appId: '1:558384286114:web:d7bbfdb189fe11b4290afb',
    messagingSenderId: '558384286114',
    projectId: 'package-app-f43fa',
    authDomain: 'package-app-f43fa.firebaseapp.com',
    storageBucket: 'package-app-f43fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ZLJkjPyOux48_q9skTSr2S5jJf-T_Ms',
    appId: '1:558384286114:android:289dcc5f5451e512290afb',
    messagingSenderId: '558384286114',
    projectId: 'package-app-f43fa',
    storageBucket: 'package-app-f43fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-oDj5cuyxpZnRgx5w4OPhRwj_FKMJ_Mg',
    appId: '1:558384286114:ios:0f7f10b7a7ee5fe8290afb',
    messagingSenderId: '558384286114',
    projectId: 'package-app-f43fa',
    storageBucket: 'package-app-f43fa.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-oDj5cuyxpZnRgx5w4OPhRwj_FKMJ_Mg',
    appId: '1:558384286114:ios:fccee9ff768dfcfc290afb',
    messagingSenderId: '558384286114',
    projectId: 'package-app-f43fa',
    storageBucket: 'package-app-f43fa.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
